version: '3.7'
services:
    postgres-service:
        image: postgres:15.1-alpine3.17
        container_name: postgres-container
        command:
            [
                'postgres',
                '-c',
                'log_statement=all',
                '-c',
                'log_destination=stderr',
                '-c',
                'log_duration=on',
            ]
        volumes:
            - postgres-volume:/var/lib/postgres/data
            - ./dump_initial.sql:/docker-entrypoint-initdb.d/dump_initial.sql
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - 5432:5432
        networks:
            - local-network
        env_file:
            - ../../.env

volumes:
    postgres-volume:
        name: postgres-volume

networks:
    local-network:
        name: local-network
