version: '3.7'
services:
    postgresql-service:
        image: postgres:15.1-alpine3.17
        container_name: postgresql-container
        command:
            [
                'postgres',
                '-c',
                'log_statement=all',
                '-c',
                'log_destination=stderr',
                '-c',
                'log_duration=on',
            ]
        volumes:
            - postgresql-volume:/var/lib/postgresql/data
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
            # POSTGRES_USER: postgres
            # POSTGRES_PASSWORD: docker
            # POSTGRES_DB: postgraphile
        ports:
            - 5432:5432
        env_file:
            - ../../.env

volumes:
    postgresql-volume:
