-- undo
DROP SCHEMA IF EXISTS app_public CASCADE;
DROP SCHEMA IF EXISTS app_private CASCADE;
DROP SCHEMA IF EXISTS app_hidden CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;

DROP ROLE user_role;

-- redo
CREATE SCHEMA IF NOT EXISTS app_public;
CREATE SCHEMA IF NOT EXISTS app_private;
CREATE SCHEMA IF NOT EXISTS app_hidden;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_private;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_hidden;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

CREATE ROLE user_role;
GRANT user_role to app_user;
