--! Previous: -
--! Hash: sha1:7e30247945e701ffa3cbabd1e281f42db817f99d

-- undo
DROP SCHEMA IF EXISTS app_public CASCADE;
DROP SCHEMA IF EXISTS app_private CASCADE;
DROP SCHEMA IF EXISTS app_hidden CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;

-- redo
CREATE SCHEMA IF NOT EXISTS app_public;
CREATE SCHEMA IF NOT EXISTS app_private;
CREATE SCHEMA IF NOT EXISTS app_hidden;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_private;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_hidden;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;
