--! Previous: -
--! Hash: sha1:a9b27cdf43b92e8bdea17cad0aad57a5055873ad

-- undo
DROP SCHEMA IF EXISTS app_public CASCADE;
DROP SCHEMA IF EXISTS app_private CASCADE;
DROP SCHEMA IF EXISTS app_hidden CASCADE;
DROP EXTENSION IF EXISTS pgcrypto CASCADE;

-- redo
CREATE SCHEMA IF NOT EXISTS app_public;
CREATE SCHEMA IF NOT EXISTS app_private;
CREATE SCHEMA IF NOT EXISTS app_hidden;

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_public;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_private;
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA app_hidden;
